### ISSUE TITLE
Problems with the parser

### ISSUE THREAD

**Issue by jeena** [indieweb/microformats2-ruby#26]
I am having problems with what I get from the parser, it looks like there is some kind of a bug or something. I am parsing this website: http://snarfed.org/2014-02-03_re-barnaby-walters-latest-php-library-extracted-from-taproo and when you use the PHP parser mf2 it seems to parse the website like expected: http://pin13.net/mf2/?url=http://snarfed.org/2014-02-03_re-barnaby-walters-latest-php-library-extracted-from-taproo but with G5/microformats2 I get this JSON: https://jeena.net/t/mf2.json

You can see that h-entry here has two URLs:

```
    "url": [
      "http://snarfed.org/",
      "http://snarfed.org/2014-02-03_re-barnaby-walters-latest-php-library-extracted-from-taproo"
    ]
```

even if the first URL shouldn't be there because it belongs either to the h-card at the top or to to the author h-card in the middle.

**Comment by veganstraightedge** [comment]
@jeena @aaronpk  I believe this is fixed in `3.0`. I just did a test and it looks good to me. Please upgrade and run your comparison too. Re-open this issue if necessary.
