### ISSUE TITLE
Remove Glenn's old test suite URLs

### ISSUE THREAD

**Issue by veganstraightedge** [indieweb/microformats2-ruby#35]
404: http://microformat2-node.jit.su

**Comment by dissolve** [comment]
do we want to remove the files themselves and all references to the domain? or just remove the rake task that pulls the most up to date versions?

The files are still there but the current test suite does not use them.  I figure if desired we could still use the old files as an additional test set

**Comment by veganstraightedge** [comment]
I think you should blow it all away. If it's not being used, resign it the the git history. If it's ever needed again, it can be dug up. But keeping speculative code around is not worth it, imo.

Also, I think all implementations using the one big fucking spec suite is better for the community.
