### ISSUE TITLE
Implement support for microformats v1

### ISSUE THREAD

**Issue by jlsuttles** [indieweb/microformats2-ruby#9]
This could farm out to something else.

**Comment by tantek** [comment]
This is necessary (at least hCalendar compat, per the h-event spec) for being able to use this in Calagator (i.e. to fix this issue: https://github.com/calagator/calagator/issues/240 ) cc: @aaronpk

See h-event spec for details:
* http://microformats.org/wiki/h-event#Parser_Compatibility

Feel free to also create separate sub-issues for each microformats2 vocabulary's back-compat parsing requirements.

**Comment by tantek** [comment]
How did I unassign? I didn't mean to!

**Comment by dissolve** [comment]
This is done in 3.0 and released
